all:
  children:
    migrator:
      hosts:
        localhost:
          ansible_connection: local
          # CORRECCIÓN 1: Ruta absoluta
          ansible_python_interpreter: /home/admin/kolla-venv/bin/python
          
          # CORRECCIÓN 2: Credenciales nuevas
          vcenter_hostname: 127.0.0.1
          vcenter_port: 8989
          vcenter_username: admin
          vcenter_password: "pass123"
          vcenter_validate_certs: false
          vcenter_datacenter: DC0
          vcenter_cluster: DC0_C0

    conversion_host:
      hosts:
        conversion_host_1:
          ansible_host: 172.28.88.195
          ansible_user: cloud-user
          ansible_ssh_private_key_file: /tmp/conversion_host.pem
          os_migrate_conversion_host_address: 172.28.88.195
          os_migrate_conversion_host_type: openstack
